/* MEDIJOY — shared i18n + nav behaviour */

const I18N = {
/* ══════════════════════ 한국어 ══════════════════════ */
ko:{
  "util.reg":"보건복지부 외국인환자 유치업자 등록","util.regno":"제 A-2025-01-02-06146 호",
  "nav.about":"회사 소개","nav.service":"서비스 안내","nav.care":"사후관리","nav.contact":"상담 신청","nav.cta":"상담 신청",

  /* ── home ── */
  "hero.eyebrow":"Global Patient Care · Korea",
  "hero.title":"글로벌 환자와<br>대한민국 대학병원을 잇는<br><b>신뢰의 가교</b>",
  "hero.sub":"경희의료원 공식 글로벌 파트너, 한국보건산업진흥원(KHIDI) 프로젝트 공식 수행 기업. 출국 준비부터 귀국 후 사후관리까지 하나의 팀이 책임집니다.",
  "hero.cta1":"상담 신청하기","hero.cta2":"서비스 자세히 보기",
  "hero.proverb":"길을 함께 가 보면 진정한 동반자를 알 수 있습니다.",
  "cred.1.t":"경희의료원 공식 글로벌 파트너",
  "cred.1.d":"비공식 브로커가 아닌 대학병원 계약 파트너로서 진료를 연계합니다.",
  "cred.2.t":"KHIDI 프로젝트 공식 수행 기업",
  "cred.2.d":"ICT 기반 몽골 중증 환자 유치 및 사후관리 선순환 플랫폼 실증사업 선정.",
  "cred.3.t":"종합여행업 등록 (제2025-000010호)",
  "cred.3.d":"항공·숙박·이동까지 여행업 등록 사업자로서 직접 설계합니다.",

  "biz.eyebrow":"Business Areas","biz.title":"메디조이의 다섯 가지 사업 영역",
  "biz.sub":"환자를 데려오는 일에서 멈추지 않습니다. 치료·회복·교육까지 의료관광의 전 단계를 사업으로 설계합니다.",
  "biz.1.t":"병원 연계 컨시어지","biz.1.tag":"For Patients",
  "biz.1.d":"경희의료원 등 국내 대학병원과의 공식 연계를 통해 중증 질환 치료와 정밀 검진을 코디네이션합니다. 의무기록 사전 검토부터 진료 일정, 통역, 체류까지 전담팀이 관리합니다.",
  "biz.2.t":"Wellness 치유 여행","biz.2.tag":"For Patients",
  "biz.2.d":"치료 후 회복 기간을 여행으로 설계합니다. 한·양방 융합 치료, 요양 프로그램, 동반 가족을 위한 일정까지 종합여행업 등록 사업자로서 직접 구성합니다.",
  "biz.3.t":"K-Food 미식 큐레이션","biz.3.tag":"For Patients",
  "biz.3.d":"환자에게는 의료진 가이드를 준수한 면역·회복 식단을, 동반 가족에게는 궁중요리를 포함한 프리미엄 한식 미식 경험을 제공합니다.",
  "biz.4.t":"외국 의료진 교육 연계","biz.4.tag":"For Partners",
  "biz.4.d":"몽골·CIS 지역 의료진을 대상으로 국내 대학병원 연수 및 임상 교육 프로그램을 연계합니다. 현지 의료 수준 향상과 환자 의뢰 네트워크가 함께 성장하는 구조입니다.",
  "biz.5.t":"의료통역사 양성 교육","biz.5.tag":"For Partners",
  "biz.5.d":"의료 현장에서 실제로 통하는 통역 인력을 직접 양성합니다. 전문 용어와 진료 프로토콜을 이해하는 통역사는 의료관광의 가장 큰 병목이자 핵심 자산입니다.",

  "why.eyebrow":"Why Medijoy","why.title":"메디조이의 차별화된 핵심 경쟁력",
  "why.1.t":"언어 & 문화적 공감","why.1.l":"단순한 통역을 넘어 문화를 이해합니다.",
  "why.1.d":"전담 몽골어 통역사를 통해 문화적 차이로 발생할 수 있는 의료적 오해를 원천 차단하고 환자의 심리적 안정을 도모합니다.",
  "why.2.t":"모든 여정을 함께하는 컨시어지","why.2.l":"낯선 환경에서도 안심할 수 있도록.",
  "why.2.d":"출국 준비부터 치료 후 안전한 귀국길까지, 환자와 동반 가족의 불편함을 최소화하는 End-to-End 케어를 제공합니다.",
  "why.3.t":"투명한 매칭","why.3.l":"경제적 부담과 불안을 덜어드립니다.",
  "why.3.d":"의료 수가를 사전에 안내하고, 대학병원과의 긴밀한 소통으로 꼭 필요한 맞춤형 치료만 진행합니다.",

  "home.j.eyebrow":"The Seamless Patient Journey","home.j.title":"출국 전부터 귀국 후까지, 끊기지 않는 하나의 흐름",
  "home.j.sub":"각 단계마다 담당자가 지정되며, 환자와 보호자는 하나의 창구로만 소통합니다.",
  "home.j.more":"케어 프로세스 전체 보기",

  "close.title":"가장 가까운 곳에서 전하는 안심, 신뢰, 회복",
  "close.sub":"타국에서의 치료가 불안하지 않도록, 메디조이가 여러분의 든든한 파트너가 되어 드리겠습니다.",
  "close.cta":"상담 신청하기",

  /* ── about ── */
  "ab.crumb":"홈 · 회사 소개","ab.eyebrow":"About Medijoy","ab.title":"메디조이는 사람을 생각합니다",
  "ab.sub":"의료 서비스의 시작과 끝에는 사람이 있습니다. 메디조이는 환자가 낯선 나라에서 겪는 불안을 줄이는 일을 사업의 본질로 봅니다.",
  "ab.g.eyebrow":"CEO Message","ab.g.title":"인사말",
  "ab.g.1":"메디조이를 찾아주셔서 감사합니다.",
  "ab.g.2":"국경을 넘는 치료에는 늘 두 가지 어려움이 따릅니다. 하나는 <strong>믿을 수 있는 의료진을 만나는 일</strong>이고, 다른 하나는 <strong>치료가 끝난 뒤에도 관리가 이어지는 일</strong>입니다. 그동안 많은 환자들이 첫 번째 문턱은 넘었지만 두 번째에서 어려움을 겪었습니다. 귀국하는 순간 진료 기록이 끊기고, 현지 주치의는 한국에서 무슨 치료를 받았는지 알 수 없었기 때문입니다.",
  "ab.g.3":"메디조이는 이 두 가지를 하나의 서비스로 연결하기 위해 시작했습니다. 경희의료원과의 공식 파트너십으로 첫 번째를, 자체 개발한 <strong>LiteracyM</strong> 사후관리 시스템으로 두 번째를 풉니다.",
  "ab.g.4":"몽골에는 이런 속담이 있습니다. <em>“길을 함께 가 보면 진정한 동반자를 알 수 있다.”</em> 메디조이는 환자의 치유 여정 전체를 함께 걷는 동반자가 되겠습니다.",
  "ab.g.sign":"메디조이 대표","ab.g.name":"한 민 이",
  "ab.side.t":"한눈에 보기",
  "ab.side.1":"설립","ab.side.1v":"2025년 6월",
  "ab.side.2":"주력 분야","ab.side.2v":"외국인환자 유치 · 의료 코디네이션",
  "ab.side.3":"주요 대상 국가","ab.side.3v":"몽골 · CIS · 유라시아",
  "ab.side.4":"연계 의료기관","ab.side.4v":"경희의료원 외",

  "ab.info.eyebrow":"Corporate Information","ab.info.title":"회사 개요 및 등록 현황",
  "ab.info.sub":"메디조이는 외국인환자 유치업과 관광사업(종합여행업)에 모두 정식 등록된 사업자입니다. 두 등록을 함께 보유한 사업자는 많지 않습니다.",
  "ab.i.name":"상호","ab.i.namev":"메디조이 (MEDIJOY)",
  "ab.i.ceo":"대표자","ab.i.ceov":"한민이",
  "ab.i.est":"개업일","ab.i.estv":"2025년 6월 9일",
  "ab.i.biz":"사업자등록번호","ab.i.bizv":"455-63-00850",
  "ab.i.addr":"소재지","ab.i.addrv":"서울특별시 강동구 올림픽로78길 30, 상가동 B108-34호<br>(천호동, 힐데스하임 천호 아파트)",
  "ab.i.type":"업종","ab.i.typev":"외국인 환자 유치업 · 여행사업 · 기타 여행 보조 및 예약 서비스업 · 경영 컨설팅업",
  "ab.i.reg1":"외국인환자 유치업자 등록","ab.i.reg1v":"제A-2025-01-02-06146호 (서울특별시장)<br>유효기간 2025.06.23 ~ 2028.06.22",
  "ab.i.reg2":"관광사업 등록","ab.i.reg2v":"제2025-000010호 종합여행업 (강동구청장)",
  "ab.i.tel":"연락처","ab.i.telv":"Tel. 02-477-1032 · Mobile. 010-8565-1032<br>contact@medijoy.co.kr",

  "adv.eyebrow":"Global Advisory Board","adv.title":"임상·약학·해외 네트워크를 아우르는 3대 자문 체계",
  "adv.sub":"글로벌 약학 안전성, 대학병원 전문 임상, 해외 외과 네트워크가 결합되어 환자에게 가장 안전한 치료 여정을 설계합니다.",
  "adv.1.n":"김철용 약사 / CSO","adv.1.r":"글로벌 제약·바이오 전문가",
  "adv.1.a":"서울대학교 약학대학 졸업","adv.1.b":"한국얀센(Janssen Korea) 전문 세일즈 경력","adv.1.c":"대조약국 대표약사 16년 · 우크라이나 진출 기업 운영",
  "adv.1.role":"국가 간 처방 의약품 동등성 및 복약 안전성 검증",
  "adv.2.n":"이상호 교수","adv.2.r":"신장내과 전문의 · 수석 자문위원",
  "adv.2.a":"신장·이식·심혈관 고난도 중증 분야","adv.2.b":"대학병원급 다학제 협진 및 글로벌 환자 진료 프로토콜 설계","adv.2.c":"환자 개별 병력에 따른 맞춤형 정밀 치료 로드맵 자문",
  "adv.2.role":"중증 환자 입국 전 1차 정밀 심의 총괄",
  "adv.3.n":"이신이 박사","adv.3.r":"외과 전문의 · 해외 의료 네트워크",
  "adv.3.a":"모스크바 국립의과대학 외과 Ph.D./M.D.","adv.3.b":"우크라이나 오데사(Odesa) 병원 개업의 역임","adv.3.c":"CIS·유라시아 환자 현지 임상 연계 및 사후 관리 지원",
  "adv.3.role":"글로벌 외과 임상 교류 및 다국어 의료 커뮤니케이션",

  /* ── service ── */
  "sv.crumb":"홈 · 서비스 안내","sv.eyebrow":"Our Service","sv.title":"글로벌 환자 원스톱 케어",
  "sv.sub":"출국 전 의무기록 검토부터 귀국 후 원격 상담까지, 치유의 여정 전 구간을 하나의 팀이 설계하고 책임집니다.",
  "journey.eyebrow":"The Seamless Patient Journey","journey.title":"세 단계로 나누어 관리합니다",
  "journey.sub":"각 단계마다 담당자가 지정되며, 환자와 보호자는 하나의 창구로만 소통합니다.",
  "j1.title":"출국 전","j1.when":"Before Arrival",
  "j1.a.t":"의무기록 사전 검토","j1.a.d":"환자의 기본 기록 확인 및 전문의 사전 심의.",
  "j1.b.t":"병원·의료진 매칭","j1.b.d":"검증된 병원 및 의료진 최적 매칭.",
  "j1.c.t":"여정 준비","j1.c.d":"비자 발급 지원, 맞춤형 숙소 추천 및 사전 예약.",
  "j2.title":"체류 중","j2.when":"In Korea",
  "j2.a.t":"입국 및 이동","j2.a.d":"공항 입국 환영(Meet & Greet) 및 전용 차량 픽업/샌딩.",
  "j2.b.t":"진료 코디네이션","j2.b.d":"1:1 전담 의료 통역 및 진료 일정 조율.",
  "j2.c.t":"24시간 대응","j2.c.d":"실시간 메신저 채널을 통한 긴급 상황 대응.",
  "j3.title":"귀국 후","j3.when":"After Return",
  "j3.a.t":"후속 관리","j3.a.d":"귀국 후 정기 상태 체크 및 필요시 한국 의료진 2차 원격 비대면 상담 연결.",
  "j3.b.t":"디지털 진료 기록","j3.b.d":"LiteracyM 앱을 통한 진료 기록 관리.",

  "prog.eyebrow":"Program Portfolio","prog.title":"메디조이 특화 프로그램",
  "prog.1.t":"중증 질환 치료",
  "prog.1.a":"신장이식, 암 치료, 심뇌혈관 질환 등 고난도 중증 질환 전문.",
  "prog.1.b":"이상호 교수 연구팀 등 최상위 임상 교수진의 다학제 통합 진료 연계.",
  "prog.2.t":"프리미엄 검진 & 웰니스",
  "prog.2.a":"VIP 건강검진센터와 연계한 1:1 맞춤형 정밀 검진.",
  "prog.2.b":"치료 후 회복 기간 동안 한·양방 융합 치료를 통한 면역 증강.",
  "prog.3.t":"맞춤형 K-미식 큐레이션",
  "prog.3.a":"<strong>환자용:</strong> 의료진 가이드를 준수한 맞춤형 면역·회복 식단 (Medical Food Track).",
  "prog.3.b":"<strong>동반 가족용:</strong> K-Food의 참맛을 느낄 수 있는 프리미엄 미식 큐레이션.",

  "br.eyebrow":"Borderless Continuity of Care","br.title":"한국에서의 진료, 몽골에서도 안전하게 이어집니다",
  "br.sub":"국경을 넘으면 끊기던 진료 기록을 LiteracyM이 현지 주치의에게 연결합니다.",
  "br.1.t":"의무기록 자동 변환","br.1.d":"한국의 진료 기록과 처방전을 몽골어로 변환하여 현지 주치의에게 전달.",
  "br.2.t":"스마트 모니터링","br.2.d":"귀국 후에도 정기적인 수치 관리 및 복약 모니터링 지속.",
  "br.3.t":"프리미엄 혜택","br.3.d":"메디조이 환자 대상 LiteracyM 6개월 무료 사용 쿠폰 제공.",
  "br.node1.s":"경희의료원","br.node1.d":"정밀 진단 및 맞춤형 수술·치료 후 체계적인 의무기록 생성.",
  "br.node2.s":"환자 & 현지 의료진","br.node2.d":"변환된 모국어 진료 데이터를 바탕으로 연속성 있는 후속 처방·치료.",

  /* ── contact ── */
  "ct.crumb":"홈 · 상담 신청","ct.eyebrow":"Contact","ct.title":"상담 신청",
  "ct.sub":"담당 코디네이터가 직접 확인 후 연락드립니다. 진단명이 확정되지 않았거나 어디서부터 시작해야 할지 모르는 경우에도 편하게 문의해 주세요.",
  "form.title":"상담 신청서","form.sub":"영업일 기준 24시간 이내에 회신드립니다.",
  "form.name":"성함","form.country":"거주 국가","form.other":"기타",
  "form.contact":"연락처 (전화 또는 이메일)","form.channel":"선호 연락 수단",
  "form.ch.phone":"전화 통화","form.ch.email":"이메일",
  "form.area":"희망 진료 분야",
  "form.area.critical":"중증 질환 치료 (이식·암·심뇌혈관)",
  "form.area.checkup":"프리미엄 정밀 검진",
  "form.area.wellness":"치료 후 회복·웰니스",
  "form.area.undecided":"아직 결정하지 못했습니다",
  "form.docs":"보유하신 의료 자료 (해당 항목 모두 선택)",
  "form.docs.hint":"지금 첨부하실 필요는 없습니다. 보유 여부만 체크해 주시면 회신 메일에서 안전하게 전달하는 방법을 안내해 드립니다. (CT·MRI 등 영상은 판독지 기준)",
  "form.docs.1":"의무기록·소견서",
  "form.docs.2":"검사 결과지",
  "form.docs.3":"영상검사 판독지",
  "form.docs.4":"아직 없음",
  "form.paid.t":"의료진 사전 검토 서비스 (유료)",
  "form.paid.d":"입국 전에 협력 의료기관 의료진의 정밀 검토가 필요한 경우, 별도 유료 서비스로 신청하실 수 있습니다. 상담 시 절차와 비용을 안내해 드립니다.",
  "form.note":"남기실 말씀","form.note.ph":"현재 상황이나 궁금한 점을 간단히 적어주세요.",
  "form.consent":"개인정보 수집·이용 및 상담 목적의 국외 이전에 동의합니다. <a href=\"privacy.html\">자세히 보기</a>",
  "form.submit":"상담 신청하기","form.sla":"접수 후 영업일 기준 24시간 이내에 회신드립니다.",
  "form.or":"또는 메신저·전화로",
  "ct.info.t":"직접 연락하기","ct.info.sub":"전화 상담은 한국 시간 기준 평일 09:00 ~ 18:00에 가능합니다.",
  "ct.i.tel":"대표 전화","ct.i.mob":"휴대전화","ct.i.mail":"이메일","ct.i.addr":"사무소",
  "ct.i.addrv":"서울특별시 강동구 올림픽로78길 30<br>상가동 B108-34호 (천호동)",
  "ct.note.t":"상담 전 알아두실 점",
  "ct.note.1":"메디조이는 의료기관이 아니므로 전화나 온라인으로 진단을 제공하지 않습니다.",
  "ct.note.2":"보유하신 의무기록·검사 결과가 있으면 상담이 훨씬 정확해집니다. 회신 메일에 전달 방법을 안내해 드립니다.",
  "ct.note.3":"치료 가능 여부와 예상 비용은 의료진의 사전 검토를 거친 뒤 안내됩니다.",

  /* ── privacy ── */
  "pv.crumb":"홈 · 개인정보처리방침","pv.eyebrow":"Privacy","pv.title":"개인정보처리방침",
  "pv.sub":"메디조이는 「개인정보 보호법」에 따라 이용자의 개인정보를 보호하고 관련 고충을 신속하게 처리하기 위하여 다음과 같이 방침을 수립·공개합니다.",

  /* ── footer ── */
  "ft.co":"메디조이 (MEDIJOY) · 대표 한민이",
  "ft.addr":"서울특별시 강동구 올림픽로78길 30, 상가동 B108-34호 (천호동, 힐데스하임 천호)",
  "ft.biz":"사업자등록번호 455-63-00850",
  "ft.reg":"외국인환자 유치업자 등록 제A-2025-01-02-06146호 (유효기간 2025.06.23 ~ 2028.06.22)",
  "ft.tour":"관광사업(종합여행업) 등록 제2025-000010호 · 강동구청",
  "ft.privacy":"개인정보처리방침","ft.contact":"상담 신청","ft.about":"회사 소개","ft.service":"서비스 안내",
  "ft.disclaimer":"메디조이는 의료기관이 아니며, 등록된 외국인환자 유치업자로서 환자와 국내 의료기관 간의 연계·통역·체류 지원 서비스를 제공합니다. 진단 및 치료에 관한 모든 의학적 판단과 책임은 진료를 담당하는 의료기관 및 의료진에게 있습니다."
},

/* ══════════════════════ 简体中文 ══════════════════════ */
zh:{
  "util.reg":"韩国保健福祉部 外国患者招引业者登记","util.regno":"第 A-2025-01-02-06146 号",
  "nav.about":"公司介绍","nav.service":"服务介绍","nav.care":"回国后管理","nav.contact":"咨询申请","nav.cta":"申请咨询",

  "hero.eyebrow":"Global Patient Care · Korea",
  "hero.title":"连接海外患者与<br>韩国顶尖大学医院的<br><b>信赖之桥</b>",
  "hero.sub":"庆熙大学医院官方全球合作伙伴，韩国保健产业振兴院（KHIDI）项目正式执行企业。从出国准备到回国后的持续管理，由同一支团队全程负责。",
  "hero.cta1":"申请咨询","hero.cta2":"查看服务详情",
  "hero.proverb":"同行一段路，方知真伙伴。（蒙古谚语）",
  "cred.1.t":"庆熙大学医院官方全球合作伙伴",
  "cred.1.d":"以大学医院的正式签约合作伙伴身份安排诊疗，而非非正式中介。",
  "cred.2.t":"KHIDI 项目正式执行企业",
  "cred.2.d":"入选基于ICT的蒙古重症患者招引及回国后管理平台实证项目。",
  "cred.3.t":"综合旅行业登记（第2025-000010号）",
  "cred.3.d":"以正式登记的旅行业者身份，自行安排机票、住宿与交通。",

  "biz.eyebrow":"Business Areas","biz.title":"美迪乔伊的五大业务领域",
  "biz.sub":"我们不止于把患者带来。从治疗、康复到教育，医疗旅行的每一个环节都被设计为完整的服务。",
  "biz.1.t":"医院对接与全程陪同","biz.1.tag":"面向患者",
  "biz.1.d":"通过与庆熙大学医院等韩国大学医院的正式合作，协调重症治疗与精密体检。从病历预审、诊疗预约、医疗翻译到在韩停留，全部由专属团队负责。",
  "biz.2.t":"Wellness 疗养旅行","biz.2.tag":"面向患者",
  "biz.2.d":"将治疗后的康复期设计成一段旅程。韩医与西医结合治疗、疗养项目、以及陪同家属的行程，均由具备综合旅行业资质的我们直接安排。",
  "biz.3.t":"定制 K-Food 美食策划","biz.3.tag":"面向患者",
  "biz.3.d":"为患者提供遵循医嘱的免疫与康复膳食；为陪同家属提供包含宫廷料理在内的高端韩式美食体验。",
  "biz.4.t":"海外医疗人员进修对接","biz.4.tag":"面向合作伙伴",
  "biz.4.d":"为蒙古及独联体地区的医疗人员对接韩国大学医院的进修与临床培训项目。当地医疗水平的提升与患者转诊网络同步成长。",
  "biz.5.t":"医疗翻译人才培养","biz.5.tag":"面向合作伙伴",
  "biz.5.d":"我们亲自培养能在真实医疗现场胜任的翻译人员。懂专业术语与诊疗流程的翻译，是这个行业最大的瓶颈，也是最核心的资产。",

  "why.eyebrow":"Why Medijoy","why.title":"美迪乔伊的核心竞争力",
  "why.1.t":"语言与文化的共鸣","why.1.l":"不只是翻译，更理解文化。",
  "why.1.d":"通过专属翻译人员，从源头阻断因文化差异引发的医疗误解，让患者保持心理上的安定。",
  "why.2.t":"全程相伴的礼宾服务","why.2.l":"即使在陌生环境也能安心。",
  "why.2.d":"从出国准备到治疗后平安返程，提供将患者与陪同家属的不便降到最低的端到端照护。",
  "why.3.t":"透明的对接","why.3.l":"减轻经济负担与不安。",
  "why.3.d":"事先说明诊疗费用，并通过与大学医院的紧密沟通，只进行确有必要的定制治疗。",

  "home.j.eyebrow":"The Seamless Patient Journey","home.j.title":"从出国前到回国后，不间断的一条动线",
  "home.j.sub":"每个阶段都有指定负责人，患者与家属只需通过一个窗口沟通。",
  "home.j.more":"查看完整服务流程",

  "close.title":"在最近的地方传递安心、信赖与康复",
  "close.sub":"为了让异国就医不再令人不安，美迪乔伊愿成为您可靠的当地伙伴。",
  "close.cta":"申请咨询",

  "ab.crumb":"首页 · 公司介绍","ab.eyebrow":"About Medijoy","ab.title":"美迪乔伊，以人为本",
  "ab.sub":"医疗服务的起点与终点都是人。减轻患者在异国他乡所感受到的不安，正是我们视为事业本质的工作。",
  "ab.g.eyebrow":"CEO Message","ab.g.title":"致辞",
  "ab.g.1":"感谢您了解美迪乔伊。",
  "ab.g.2":"跨境就医始终伴随两个难题。一是<strong>能否遇到值得信赖的医疗团队</strong>，二是<strong>治疗结束后管理能否延续</strong>。过去许多患者跨过了第一道门槛，却在第二道上受阻——回国的那一刻，诊疗记录就断了，当地主治医生无从知晓患者在韩国接受了怎样的治疗。",
  "ab.g.3":"美迪乔伊正是为了把这两者连成一项服务而创立。与庆熙大学医院的正式合作解决第一个问题，自主开发的<strong>LiteracyM</strong> 回国后管理系统解决第二个问题。",
  "ab.g.4":"蒙古有句谚语：<em>“同行一段路，方知真伙伴。”</em> 美迪乔伊愿做陪伴患者走完整段康复旅程的同行者。",
  "ab.g.sign":"美迪乔伊 代表","ab.g.name":"韩 玟 伊",
  "ab.side.t":"一览",
  "ab.side.1":"成立","ab.side.1v":"2025年6月",
  "ab.side.2":"核心领域","ab.side.2v":"外国患者招引 · 诊疗协调",
  "ab.side.3":"主要目标国家","ab.side.3v":"中国 · 蒙古 · 俄罗斯",
  "ab.side.4":"合作医疗机构","ab.side.4v":"庆熙大学医院等",

  "ab.info.eyebrow":"Corporate Information","ab.info.title":"公司概况与资质登记",
  "ab.info.sub":"美迪乔伊同时持有外国患者招引业与综合旅行业两项正式登记。同时具备两者的企业并不多见。",
  "ab.i.name":"公司名称","ab.i.namev":"美迪乔伊 MEDIJOY（메디조이）",
  "ab.i.ceo":"代表","ab.i.ceov":"韩玟伊（한민이 / HAN MIN I）",
  "ab.i.est":"开业日","ab.i.estv":"2025年6月9日",
  "ab.i.biz":"营业执照号","ab.i.bizv":"455-63-00850",
  "ab.i.addr":"地址","ab.i.addrv":"韩国首尔特别市江东区奥林匹克路78街30号<br>商街栋 B108-34室（千户洞）",
  "ab.i.type":"经营范围","ab.i.typev":"外国患者招引业 · 旅行业 · 预订服务业 · 经营咨询业",
  "ab.i.reg1":"外国患者招引业者登记","ab.i.reg1v":"第A-2025-01-02-06146号（首尔特别市市长）<br>有效期 2025.06.23 ~ 2028.06.22",
  "ab.i.reg2":"旅游事业登记","ab.i.reg2v":"第2025-000010号 综合旅行业（江东区厅长）",
  "ab.i.tel":"联系方式","ab.i.telv":"Tel. +82-2-477-1032 · Mobile. +82-10-8565-1032<br>contact@medijoy.co.kr",

  "adv.eyebrow":"Global Advisory Board","adv.title":"临床、药学与海外网络三位一体的顾问体系",
  "adv.sub":"国际药学安全性、大学医院的专业临床、海外外科网络相结合，为患者设计最安全的治疗路径。",
  "adv.1.n":"金哲龙 药师 / CSO","adv.1.r":"国际制药与生物专家",
  "adv.1.a":"首尔大学药学院毕业","adv.1.b":"韩国杨森（Janssen Korea）专业销售经历","adv.1.c":"大朝药局代表药师16年 · 曾在乌克兰经营企业",
  "adv.1.role":"负责跨国处方药等效性与用药安全性验证",
  "adv.2.n":"李相浩 教授","adv.2.r":"肾脏内科专科医师 · 首席顾问",
  "adv.2.a":"肾脏、移植、心血管高难度重症领域","adv.2.b":"大学医院级多学科会诊及国际患者诊疗方案设计","adv.2.c":"依据个体病史提供定制精准治疗路线图",
  "adv.2.role":"统筹重症患者入境前的初次精密审查",
  "adv.3.n":"李信伊 博士","adv.3.r":"外科专科医师 · 海外医疗网络",
  "adv.3.a":"莫斯科国立医科大学外科 Ph.D./M.D.","adv.3.b":"曾在乌克兰敖德萨开设诊所","adv.3.c":"独联体及欧亚地区患者的当地临床对接与后续管理",
  "adv.3.role":"负责国际外科临床交流与多语种医疗沟通",

  "sv.crumb":"首页 · 服务介绍","sv.eyebrow":"Our Service","sv.title":"国际患者一站式照护",
  "sv.sub":"从出国前的病历审查到回国后的远程咨询，整段康复旅程由同一支团队设计并负责。",
  "journey.eyebrow":"The Seamless Patient Journey","journey.title":"分三个阶段进行管理",
  "journey.sub":"每个阶段都有指定负责人，患者与家属只需通过一个窗口沟通。",
  "j1.title":"出国前","j1.when":"Before Arrival",
  "j1.a.t":"病历预先审查","j1.a.d":"确认患者基本病历并由专科医师事先审议。",
  "j1.b.t":"医院与医师匹配","j1.b.d":"匹配经过验证的医院与医疗团队。",
  "j1.c.t":"行程准备","j1.c.d":"协助签证办理、推荐合适住宿并提前预订。",
  "j2.title":"在韩期间","j2.when":"In Korea",
  "j2.a.t":"入境与交通","j2.a.d":"机场接机（Meet & Greet）及专车接送。",
  "j2.b.t":"诊疗协调","j2.b.d":"1对1专属医疗翻译与诊疗日程安排。",
  "j2.c.t":"24小时应对","j2.c.d":"通过即时通讯渠道处理紧急状况。",
  "j3.title":"回国后","j3.when":"After Return",
  "j3.a.t":"后续管理","j3.a.d":"定期状态回访，必要时对接韩国医疗团队的二次远程咨询。",
  "j3.b.t":"电子诊疗记录","j3.b.d":"通过 LiteracyM 应用管理诊疗记录。",

  "prog.eyebrow":"Program Portfolio","prog.title":"美迪乔伊特色项目",
  "prog.1.t":"重症疾病治疗",
  "prog.1.a":"专注肾移植、肿瘤治疗、心脑血管疾病等高难度重症领域。",
  "prog.1.b":"对接以李相浩教授研究团队为代表的顶级临床教授团的多学科综合诊疗。",
  "prog.2.t":"高端体检与康养",
  "prog.2.a":"与VIP健康体检中心联动的1对1定制精密体检。",
  "prog.2.b":"治疗后的康复期，通过韩医与西医结合治疗提升免疫力。",
  "prog.3.t":"定制 K-Food 美食策划",
  "prog.3.a":"<strong>患者：</strong>遵循医嘱的定制免疫与康复膳食（Medical Food Track）。",
  "prog.3.b":"<strong>陪同家属：</strong>可品味地道韩食的高端美食策划。",

  "br.eyebrow":"Borderless Continuity of Care","br.title":"在韩国接受的治疗，回国后也能安全延续",
  "br.sub":"过去一跨境就中断的诊疗记录，由 LiteracyM 连接到当地主治医生。",
  "br.1.t":"病历自动转换","br.1.d":"将韩国的诊疗记录与处方转换为患者母语，交付当地主治医生。",
  "br.2.t":"智能监测","br.2.d":"回国后仍持续进行指标管理与用药监测。",
  "br.3.t":"专属权益","br.3.d":"美迪乔伊患者可获赠 LiteracyM 六个月免费使用券。",
  "br.node1.s":"庆熙大学医院","br.node1.d":"完成精密诊断与定制手术、治疗后，生成系统化的诊疗记录。",
  "br.node2.s":"患者与当地医生","br.node2.d":"基于转换后的母语诊疗数据，延续后续处方与治疗。",

  "ct.crumb":"首页 · 咨询申请","ct.eyebrow":"Contact","ct.title":"咨询申请",
  "ct.sub":"专属协调员将亲自确认后与您联系。即使尚未确诊，或不知从何开始，也欢迎随时咨询。",
  "form.title":"咨询申请表","form.sub":"我们将在一个工作日（24小时）内回复。",
  "form.name":"姓名","form.country":"居住国家","form.other":"其他",
  "form.contact":"联系方式（电话或邮箱）","form.channel":"希望的联系方式",
  "form.ch.phone":"电话","form.ch.email":"电子邮件",
  "form.area":"希望的诊疗领域",
  "form.area.critical":"重症疾病治疗（移植·肿瘤·心脑血管）",
  "form.area.checkup":"高端精密体检",
  "form.area.wellness":"治疗后康复与康养",
  "form.area.undecided":"尚未确定",
  "form.docs":"您已持有的医疗资料（可多选）",
  "form.docs.hint":"现在无需上传。只要勾选持有情况，我们会在回复邮件中说明安全的传送方式。（CT、MRI 等影像以报告单为准）",
  "form.docs.1":"病历·诊断证明",
  "form.docs.2":"检查结果单",
  "form.docs.3":"影像检查报告单",
  "form.docs.4":"暂时没有",
  "form.paid.t":"医疗团队预先审查服务（收费）",
  "form.paid.d":"若在入境前需要合作医疗机构医疗团队的精密审查，可作为单独的收费服务申请。具体流程与费用将在咨询时说明。",
  "form.note":"留言","form.note.ph":"请简要写下目前的情况或想了解的问题。",
  "form.consent":"本人同意收集使用个人信息，并同意为咨询目的将其传输至境外。<a href=\"privacy.html\">查看详情</a>",
  "form.submit":"提交咨询申请","form.sla":"受理后将在一个工作日（24小时）内回复。",
  "form.or":"或通过以下方式联系",
  "ct.info.t":"直接联系","ct.info.sub":"电话咨询时间为韩国时间工作日 09:00 ~ 18:00。",
  "ct.i.tel":"公司电话","ct.i.mob":"手机","ct.i.mail":"电子邮件","ct.i.addr":"办公室",
  "ct.i.addrv":"韩国首尔特别市江东区奥林匹克路78街30号<br>商街栋 B108-34室（千户洞）",
  "ct.note.t":"咨询前请了解",
  "ct.note.1":"美迪乔伊并非医疗机构，因此不会通过电话或线上提供诊断。",
  "ct.note.2":"如持有病历或检查结果，咨询会准确得多。我们将在回复邮件中说明传送方式。",
  "ct.note.3":"能否治疗及预估费用，需经医疗团队事先审查后告知。",

  "pv.crumb":"首页 · 隐私政策","pv.eyebrow":"Privacy","pv.title":"隐私政策",
  "pv.sub":"美迪乔伊依据韩国《个人信息保护法》保护用户的个人信息。本政策以韩文版本为准。",

  "ft.co":"美迪乔伊 MEDIJOY · 代表 韩玟伊",
  "ft.addr":"韩国首尔特别市江东区奥林匹克路78街30号 商街栋 B108-34室（千户洞）",
  "ft.biz":"营业执照号 455-63-00850",
  "ft.reg":"外国患者招引业者登记 第A-2025-01-02-06146号（有效期 2025.06.23 ~ 2028.06.22）",
  "ft.tour":"旅游事业（综合旅行业）登记 第2025-000010号 · 江东区厅",
  "ft.privacy":"隐私政策","ft.contact":"咨询申请","ft.about":"公司介绍","ft.service":"服务介绍",
  "ft.disclaimer":"美迪乔伊并非医疗机构，而是作为已登记的外国患者招引业者，提供患者与韩国医疗机构之间的对接、翻译及在韩停留支援服务。有关诊断与治疗的一切医学判断及责任，均由实施诊疗的医疗机构及医务人员承担。"
},

/* ══════════════════════ Монгол ══════════════════════ */
mn:{
  "util.reg":"БНСУ-ын Эрүүл Мэндийн Яамны албан ёсны бүртгэл","util.regno":"A-2025-01-02-06146",
  "nav.about":"Бидний тухай","nav.service":"Үйлчилгээ","nav.care":"Дараах хяналт","nav.contact":"Зөвлөгөө авах","nav.cta":"Зөвлөгөө авах",

  "hero.eyebrow":"Global Patient Care · Korea",
  "hero.title":"Гадаад өвчтөн болон<br>Солонгосын их сургуулийн эмнэлгийг<br><b>холбох итгэлийн гүүр</b>",
  "hero.sub":"Кёнхи их сургуулийн эмнэлгийн албан ёсны глобал түнш, KHIDI төслийн албан ёсны гүйцэтгэгч. Явахаас өмнөх бэлтгэлээс эх орондоо буцсаны дараах хяналт хүртэл нэг баг хариуцна.",
  "hero.cta1":"Зөвлөгөө авах","hero.cta2":"Үйлчилгээг дэлгэрэнгүй үзэх",
  "hero.proverb":"Аян замд хамт явж үзвэл жинхэнэ нөхрөө таньдаг.",
  "cred.1.t":"Кёнхи эмнэлгийн албан ёсны глобал түнш",
  "cred.1.d":"Албан бус зуучлагч биш, их сургуулийн эмнэлэгтэй гэрээт түншийн хувьд эмчилгээг зохион байгуулна.",
  "cred.2.t":"KHIDI төслийн албан ёсны гүйцэтгэгч",
  "cred.2.d":"ICT суурьтай монгол хүнд өвчтөнг хүлээн авах, дараах хяналтын платформын туршилтын төсөлд сонгогдсон.",
  "cred.3.t":"Аялал жуулчлалын албан ёсны бүртгэл (№2025-000010)",
  "cred.3.d":"Нислэг, байр, тээврийг бүртгэлтэй байгууллагын хувьд өөрсдөө зохион байгуулна.",

  "biz.eyebrow":"Business Areas","biz.title":"Medijoy-гийн таван үндсэн чиглэл",
  "biz.sub":"Өвчтөнг авчрахаар зогсохгүй. Эмчилгээ, сэргэлт, боловсрол хүртэл эмнэлгийн аялал жуулчлалын бүх үе шатыг бизнес болгон зохион байгуулна.",
  "biz.1.t":"Эмнэлгийн холболт ба консьерж","biz.1.tag":"For Patients",
  "biz.1.d":"Кёнхи эмнэлэг зэрэг Солонгосын их сургуулийн эмнэлэгтэй албан ёсны холбооны хүрээнд хүнд өвчний эмчилгээ, нарийвчилсан үзлэгийг зохицуулна. Бичиг баримтын урьдчилсан хяналтаас эхлээд цаг захиалга, орчуулга, оршин суух хүртэл хариуцсан баг удирдана.",
  "biz.2.t":"Wellness эдгэрлийн аялал","biz.2.tag":"For Patients",
  "biz.2.d":"Эмчилгээний дараах сэргэлтийн хугацааг аялал болгон төлөвлөнө. Уламжлалт болон орчин үеийн анагаахын хосолсон эмчилгээ, сувиллын хөтөлбөр, хамт ирсэн гэр бүлийн хуваарийг бүртгэлтэй аялал жуулчлалын байгууллагын хувьд өөрсдөө бүрдүүлнэ.",
  "biz.3.t":"K-Food хоолны хөтөлбөр","biz.3.tag":"For Patients",
  "biz.3.d":"Өвчтөнд эмчийн зөвлөмжид нийцсэн дархлаа сэргээх хоолны дэглэм, хамт ирсэн гэр бүлд ордны хоол багтсан дээд зэрэглэлийн солонгос хоолны туршлагыг санал болгоно.",
  "biz.4.t":"Гадаад эмч нарын сургалтын холболт","biz.4.tag":"For Partners",
  "biz.4.d":"Монгол болон ТУХН-ийн эмч нарыг Солонгосын их сургуулийн эмнэлэгт дадлага, эмнэлзүйн сургалтад хамруулна. Нутгийн эмнэлгийн түвшин дээшилж, өвчтөн илгээх сүлжээ зэрэг хөгждөг бүтэц юм.",
  "biz.5.t":"Эмнэлгийн орчуулагч бэлтгэх сургалт","biz.5.tag":"For Partners",
  "biz.5.d":"Эмнэлгийн орчинд бодитоор ажиллах орчуулагчдыг өөрсдөө бэлтгэнэ. Мэргэжлийн нэр томьёо, эмчилгээний протоколыг ойлгодог орчуулагч бол энэ салбарын хамгийн том саад бөгөөд хамгийн чухал хөрөнгө.",

  "why.eyebrow":"Why Medijoy","why.title":"Medijoy-гийн онцлог давуу тал",
  "why.1.t":"Хэл, соёлын ойлголцол","why.1.l":"Зүгээр орчуулга биш, соёлыг нь ойлгоно.",
  "why.1.d":"Монгол хэлний хариуцсан орчуулагчаар дамжуулан соёлын ялгаанаас үүдэх эмнэлгийн буруу ойлголтыг таслан зогсоож, өвчтөний сэтгэл санааг тайван байлгана.",
  "why.2.t":"Бүх аяллыг хамт өнгөрөөх консьерж","why.2.l":"Танил бус орчинд ч санаа амар байхын тулд.",
  "why.2.d":"Явахын бэлтгэлээс эмчилгээний дараах аюулгүй буцалт хүртэл өвчтөн болон хамт ирсэн гэр бүлийн төвөгийг багасгасан бүрэн үйлчилгээ.",
  "why.3.t":"Ил тод сонголт","why.3.l":"Санхүүгийн дарамт, түгшүүрийг хөнгөвчилнө.",
  "why.3.d":"Эмчилгээний төлбөрийг урьдчилан мэдэгдэж, их сургуулийн эмнэлэгтэй нягт харилцан зөвхөн зайлшгүй шаардлагатай эмчилгээг хийнэ.",

  "home.j.eyebrow":"The Seamless Patient Journey","home.j.title":"Явахаас өмнөхөөс буцаж ирсний дараа хүртэл тасралтгүй нэг урсгал",
  "home.j.sub":"Үе шат бүрд хариуцсан ажилтан томилогдож, өвчтөн болон ар гэрийнхэн ганц цонхоор харилцана.",
  "home.j.more":"Үйлчилгээний бүх явцыг үзэх",

  "close.title":"Хамгийн ойроос хүргэх амар тайван байдал, итгэл, эдгэрэл",
  "close.sub":"Гадаад улсад эмчлүүлэх нь сэтгэл зовоохгүйн тулд Medijoy таны найдвартай түнш болно.",
  "close.cta":"Зөвлөгөө авах хүсэлт илгээх",

  "ab.crumb":"Нүүр · Бидний тухай","ab.eyebrow":"About Medijoy","ab.title":"Medijoy хүнийг боддог",
  "ab.sub":"Эмнэлгийн үйлчилгээний эхлэл ба төгсгөлд хүн байдаг. Өвчтөн танил бус оронд мэдэрдэг түгшүүрийг багасгахыг бид ажлынхаа мөн чанар гэж үздэг.",
  "ab.g.eyebrow":"CEO Message","ab.g.title":"Мэндчилгээ",
  "ab.g.1":"Medijoy-г сонгосон танд баярлалаа.",
  "ab.g.2":"Хил давсан эмчилгээнд үргэлж хоёр бэрхшээл дагалддаг. Нэг нь <strong>итгэж болох эмчтэй уулзах</strong>, нөгөө нь <strong>эмчилгээ дууссаны дараа ч хяналт үргэлжлэх</strong> явдал юм. Өмнө нь олон өвчтөн эхний саадыг давсан ч хоёр дахьд нь бэрхшээлтэй тулгардаг байлаа. Эх орондоо буцахад эмчилгээний бичлэг тасарч, нутгийн эмч Солонгост ямар эмчилгээ хийлгэснийг мэдэх боломжгүй байсан.",
  "ab.g.3":"Medijoy эдгээр хоёрыг нэг үйлчилгээ болгон холбохоор үүссэн. Кёнхи эмнэлэгтэй байгуулсан албан ёсны түншлэлээр эхнийхийг, өөрсдийн боловсруулсан <strong>LiteracyM</strong> системээр хоёр дахийг шийднэ.",
  "ab.g.4":"Монголд ийм зүйр үг бий: <em>“Аян замд нөхөр танигдана.”</em> Medijoy өвчтөний эдгэрлийн бүхий л замыг хамт туулах нөхөр байх болно.",
  "ab.g.sign":"Medijoy захирал","ab.g.name":"ХАН МИН И",
  "ab.side.t":"Товч танилцуулга",
  "ab.side.1":"Үүсгэн байгуулагдсан","ab.side.1v":"2025 оны 6 сар",
  "ab.side.2":"Үндсэн чиглэл","ab.side.2v":"Гадаад өвчтөн зуучлал · эмнэлгийн зохицуулалт",
  "ab.side.3":"Гол зорилтот улс","ab.side.3v":"Монгол · ТУХН · Евразия",
  "ab.side.4":"Хамтрагч эмнэлэг","ab.side.4v":"Кёнхи их сургуулийн эмнэлэг зэрэг",

  "ab.info.eyebrow":"Corporate Information","ab.info.title":"Компанийн мэдээлэл ба бүртгэл",
  "ab.info.sub":"Medijoy нь гадаад өвчтөн зуучлах болон аялал жуулчлалын аль алинд нь албан ёсоор бүртгэлтэй. Хоёуланг нь хамт эзэмшдэг байгууллага цөөн байдаг.",
  "ab.i.name":"Нэр","ab.i.namev":"MEDIJOY (메디조이)",
  "ab.i.ceo":"Захирал","ab.i.ceov":"ХАН МИН И (한민이)",
  "ab.i.est":"Үйл ажиллагаа эхэлсэн","ab.i.estv":"2025 оны 6 сарын 9",
  "ab.i.biz":"Бизнесийн бүртгэлийн дугаар","ab.i.bizv":"455-63-00850",
  "ab.i.addr":"Хаяг","ab.i.addrv":"B108-34, 30 Olympic-ro 78-gil, Gangdong-gu,<br>Сөүл, БНСУ",
  "ab.i.type":"Үйл ажиллагааны чиглэл","ab.i.typev":"Гадаад өвчтөн зуучлал · аялал жуулчлал · захиалгын үйлчилгээ · менежментийн зөвлөх",
  "ab.i.reg1":"Гадаад өвчтөн зуучлалын бүртгэл","ab.i.reg1v":"№A-2025-01-02-06146 (Сөүл хотын захирагч)<br>Хүчинтэй хугацаа 2025.06.23 ~ 2028.06.22",
  "ab.i.reg2":"Аялал жуулчлалын бүртгэл","ab.i.reg2v":"№2025-000010 (Кандон дүүргийн засаг дарга)",
  "ab.i.tel":"Холбоо барих","ab.i.telv":"Tel. +82-2-477-1032 · Mobile. +82-10-8565-1032<br>contact@medijoy.co.kr",

  "adv.eyebrow":"Global Advisory Board","adv.title":"Эмнэлзүй, эм зүй, гадаад сүлжээг хамарсан 3 баганат зөвлөх тогтолцоо",
  "adv.sub":"Олон улсын эм зүйн аюулгүй байдал, их сургуулийн эмнэлгийн мэргэжлийн эмнэлзүй, гадаад мэс заслын сүлжээ нэгдэж, өвчтөнд хамгийн аюулгүй эмчилгээний замыг зохион байгуулна.",
  "adv.1.n":"Ким Чёл Ён, эм зүйч / CSO","adv.1.r":"Олон улсын эм, био технологийн мэргэжилтэн",
  "adv.1.a":"Сөүлийн Их Сургуулийн Эм зүйн сургууль төгссөн","adv.1.b":"Janssen Korea-д мэргэжлийн борлуулалтын туршлагатай","adv.1.c":"Дэжо эмийн сангийн захирал эм зүйч 16 жил · Украинд бизнес эрхэлж байсан",
  "adv.1.role":"Улс хоорондын жороор олгох эмийн дүйцэл, эм хэрэглэх аюулгүй байдлын баталгаажуулалт",
  "adv.2.n":"Профессор И Сан Хо","adv.2.r":"Бөөрний эмгэг судлалын эмч · Ахлах зөвлөх",
  "adv.2.a":"Бөөр, эрхтэн шилжүүлэн суулгах, зүрх судасны хүнд тохиолдол","adv.2.b":"Их сургуулийн эмнэлгийн олон салбарын хамтарсан үзлэг, гадаад өвчтөний эмчилгээний протокол","adv.2.c":"Өвчний түүхэд тулгуурласан нарийвчилсан эмчилгээний төлөвлөгөөний зөвлөгөө",
  "adv.2.role":"Хүнд өвчтөн ирэхээс өмнөх анхан шатны нарийвчилсан хяналт",
  "adv.3.n":"Доктор И Шин И","adv.3.r":"Мэс заслын эмч · Гадаад эмнэлгийн сүлжээ",
  "adv.3.a":"Москвагийн Улсын Анагаахын Их Сургуулийн мэс заслын Ph.D./M.D.","adv.3.b":"Украины Одесса хотод эмнэлэг эрхэлж байсан","adv.3.c":"ТУХН болон Евразийн өвчтөний нутгийн эмнэлзүйн холбоо, дараах хяналт",
  "adv.3.role":"Олон улсын мэс заслын эмнэлзүйн солилцоо, олон хэлний эмнэлгийн харилцаа",

  "sv.crumb":"Нүүр · Үйлчилгээ","sv.eyebrow":"Our Service","sv.title":"Гадаад өвчтөний бүрэн хамрах үйлчилгээ",
  "sv.sub":"Явахаас өмнөх бичиг баримтын хяналтаас буцсаны дараах цахим зөвлөгөө хүртэл эдгэрлийн бүх замыг нэг баг зохион байгуулж хариуцна.",
  "journey.eyebrow":"The Seamless Patient Journey","journey.title":"Гурван үе шатаар удирдана",
  "journey.sub":"Үе шат бүрд хариуцсан ажилтан томилогдож, өвчтөн болон ар гэрийнхэн ганц цонхоор харилцана.",
  "j1.title":"Явахаас өмнө","j1.when":"Before Arrival",
  "j1.a.t":"Эмнэлгийн бичиг баримтын урьдчилсан хяналт","j1.a.d":"Өвчтөний үндсэн бичлэгийг шалгаж, мэргэжлийн эмч урьдчилан хянана.",
  "j1.b.t":"Эмнэлэг, эмчийн сонголт","j1.b.d":"Баталгаажсан эмнэлэг, эмчийн оновчтой тохируулга.",
  "j1.c.t":"Аяллын бэлтгэл","j1.c.d":"Виз мэдүүлэхэд туслах, тохирох байр санал болгож урьдчилан захиалах.",
  "j2.title":"Солонгост байхад","j2.when":"In Korea",
  "j2.a.t":"Ирэлт ба тээвэр","j2.a.d":"Нисэх буудал дээр угтах (Meet & Greet), тусгай тээврийн үйлчилгээ.",
  "j2.b.t":"Эмчилгээний зохицуулалт","j2.b.d":"1:1 эмнэлгийн орчуулагч болон эмчилгээний хуваарийн зохицуулалт.",
  "j2.c.t":"24 цагийн дэмжлэг","j2.c.d":"Мессенжер сувгаар яаралтай нөхцөлд шуурхай хариу үйлдэл.",
  "j3.title":"Буцаж ирсний дараа","j3.when":"After Return",
  "j3.a.t":"Дараах хяналт","j3.a.d":"Тогтмол байдлын хяналт, шаардлагатай бол солонгос эмчтэй цахимаар давтан зөвлөгөө.",
  "j3.b.t":"Цахим эмнэлгийн бичлэг","j3.b.d":"LiteracyM аппаар эмчилгээний бичлэгийн удирдлага.",

  "prog.eyebrow":"Program Portfolio","prog.title":"Medijoy-гийн тусгай хөтөлбөрүүд",
  "prog.1.t":"Хүнд өвчний эмчилгээ",
  "prog.1.a":"Бөөр шилжүүлэн суулгах, хавдрын эмчилгээ, зүрх тархины судасны өвчин зэрэг хүндрэлтэй тохиолдол.",
  "prog.1.b":"Профессор И Сан Хогийн баг зэрэг тэргүүлэх эмнэлзүйн профессоруудын нэгдсэн үзлэгийн холболт.",
  "prog.2.t":"Дээд зэрэглэлийн үзлэг ба сэргээн засалт",
  "prog.2.a":"VIP эрүүл мэндийн үзлэгийн төвтэй хамтарсан 1:1 нарийвчилсан үзлэг.",
  "prog.2.b":"Эмчилгээний дараах сэргэлтийн хугацаанд уламжлалт ба орчин үеийн анагаахын хосолсон эмчилгээгээр дархлаа сайжруулах.",
  "prog.3.t":"Хувийн K-Food хоолны хөтөлбөр",
  "prog.3.a":"<strong>Өвчтөнд:</strong> Эмчийн зөвлөмжид нийцсэн дархлаа сэргээх хоолны дэглэм (Medical Food Track).",
  "prog.3.b":"<strong>Хамт ирсэн гэр бүлд:</strong> Солонгос хоолны жинхэнэ амтыг мэдрэх дээд зэрэглэлийн хөтөлбөр.",

  "br.eyebrow":"Borderless Continuity of Care","br.title":"Солонгост хийлгэсэн эмчилгээ Монголд ч аюулгүй үргэлжилнэ",
  "br.sub":"Хил давахад тасалддаг байсан эмнэлгийн бичлэгийг LiteracyM нутгийн эмчид холбож өгнө.",
  "br.1.t":"Эмнэлгийн бичлэгийн автомат хөрвүүлэлт","br.1.d":"Солонгос дахь эмчилгээний бичлэг, жорыг монгол хэл рүү хөрвүүлж нутгийн эмчид дамжуулна.",
  "br.2.t":"Ухаалаг хяналт","br.2.d":"Эх орондоо буцсаны дараа ч үзүүлэлтийн хяналт, эм хэрэглэлтийн мониторинг үргэлжилнэ.",
  "br.3.t":"Онцгой давуу тал","br.3.d":"Medijoy-гийн өвчтөнд LiteracyM-г 6 сар үнэгүй ашиглах эрх олгоно.",
  "br.node1.s":"Кёнхи эмнэлэг","br.node1.d":"Нарийвчилсан оношилгоо, мэс засал, эмчилгээний дараа системтэй эмнэлгийн бичлэг үүсгэнэ.",
  "br.node2.s":"Өвчтөн ба нутгийн эмч","br.node2.d":"Эх хэл рүү хөрвүүлсэн өгөгдлийн үндсэн дээр тасралтгүй жор, эмчилгээ үргэлжилнэ.",

  "ct.crumb":"Нүүр · Зөвлөгөө авах","ct.eyebrow":"Contact","ct.title":"Зөвлөгөө авах хүсэлт",
  "ct.sub":"Хариуцсан зохицуулагч шууд шалгаад холбогдоно. Онош тодорхойгүй, эсвэл хаанаас эхлэхээ мэдэхгүй байсан ч чөлөөтэй хандаарай.",
  "form.title":"Хүсэлтийн маягт","form.sub":"Ажлын 24 цагийн дотор хариу өгнө.",
  "form.name":"Нэр","form.country":"Оршин суугаа улс","form.other":"Бусад",
  "form.contact":"Холбоо барих (утас эсвэл и-мэйл)","form.channel":"Холбогдох сувгийн сонголт",
  "form.ch.phone":"Утсаар","form.ch.email":"И-мэйл",
  "form.area":"Хүсэж буй эмчилгээний чиглэл",
  "form.area.critical":"Хүнд өвчний эмчилгээ (шилжүүлэн суулгах, хавдар, зүрх судас)",
  "form.area.checkup":"Дээд зэрэглэлийн нарийвчилсан үзлэг",
  "form.area.wellness":"Эмчилгээний дараах сэргээн засах",
  "form.area.undecided":"Хараахан шийдээгүй байна",
  "form.docs":"Танд байгаа эмнэлгийн бичиг баримт (тохирохыг бүгдийг сонгоно уу)",
  "form.docs.hint":"Одоо хавсаргах шаардлагагүй. Зөвхөн байгаа эсэхийг мэдэгдэхэд хангалттай — хариу и-мэйлд аюулгүй илгээх аргыг тайлбарлана.",
  "form.docs.1":"Эмнэлгийн бичлэг, дүгнэлт",
  "form.docs.2":"Шинжилгээний хариу",
  "form.docs.3":"Дүрс оношилгооны дүгнэлт",
  "form.docs.4":"Одоогоор байхгүй",
  "form.paid.t":"Эмчийн урьдчилсан нарийвчилсан хяналт (төлбөртэй)",
  "form.paid.d":"Солонгост ирэхээс өмнө хамтрагч эмнэлгийн эмч нарын нарийвчилсан хяналт шаардлагатай бол тусдаа төлбөртэй үйлчилгээгээр хүсэлт гаргах боломжтой. Зөвлөгөөний үеэр журам, зардлыг тайлбарлана.",
  "form.note":"Нэмэлт мэдээлэл","form.note.ph":"Одоогийн байдал эсвэл асуух зүйлээ товч бичнэ үү.",
  "form.consent":"Хувийн мэдээллийг цуглуулах, ашиглах болон зөвлөгөөний зорилгоор гадаад улсад дамжуулахыг зөвшөөрч байна. <a href=\"privacy.html\">Дэлгэрэнгүй</a>",
  "form.submit":"Хүсэлт илгээх","form.sla":"Хүсэлтийг хүлээн авснаас хойш ажлын 24 цагийн дотор хариу өгнө.",
  "form.or":"эсвэл мессенжер, утсаар",
  "ct.info.t":"Шууд холбогдох","ct.info.sub":"Утсаар зөвлөгөө авах боломжтой цаг: Солонгосын цагаар ажлын өдрүүдэд 09:00 ~ 18:00.",
  "ct.i.tel":"Албаны утас","ct.i.mob":"Гар утас","ct.i.mail":"И-мэйл","ct.i.addr":"Оффис",
  "ct.i.addrv":"B108-34, 30 Olympic-ro 78-gil,<br>Gangdong-gu, Сөүл, БНСУ",
  "ct.note.t":"Зөвлөгөө авахаас өмнө анхаарах зүйл",
  "ct.note.1":"Medijoy нь эмнэлгийн байгууллага биш тул утсаар болон онлайнаар онош тавихгүй.",
  "ct.note.2":"Эмнэлгийн бичлэг, шинжилгээний хариу байвал зөвлөгөө илүү нарийвчлалтай болно. Хариу и-мэйлд илгээх аргыг тайлбарлана.",
  "ct.note.3":"Эмчлэх боломжтой эсэх, зардлын урьдчилсан тооцоог эмч нарын хяналтын дараа мэдэгдэнэ.",

  "pv.crumb":"Нүүр · Нууцлалын бодлого","pv.eyebrow":"Privacy","pv.title":"Нууцлалын бодлого",
  "pv.sub":"Medijoy нь БНСУ-ын «Хувийн мэдээлэл хамгаалах тухай хууль»-ийн дагуу хэрэглэгчийн хувийн мэдээллийг хамгаална. Албан ёсны эх хувь нь солонгос хэл дээрх хувилбар болно.",

  "ft.co":"MEDIJOY · Захирал ХАН МИН И",
  "ft.addr":"B108-34, 30 Olympic-ro 78-gil, Gangdong-gu, Сөүл, БНСУ",
  "ft.biz":"Бизнесийн бүртгэлийн дугаар 455-63-00850",
  "ft.reg":"Гадаад өвчтөн зуучлах бүртгэл №A-2025-01-02-06146 (2025.06.23 ~ 2028.06.22)",
  "ft.tour":"Аялал жуулчлалын бүртгэл №2025-000010 · Кандон дүүрэг",
  "ft.privacy":"Нууцлалын бодлого","ft.contact":"Зөвлөгөө авах","ft.about":"Бидний тухай","ft.service":"Үйлчилгээ",
  "ft.disclaimer":"Medijoy нь эмнэлгийн байгууллага биш бөгөөд бүртгэлтэй зуучлагчийн хувьд өвчтөн болон Солонгосын эмнэлгийн байгууллагын хооронд холбоо, орчуулга, оршин суух дэмжлэг үзүүлдэг. Онош, эмчилгээтэй холбоотой бүх эмнэлгийн шийдвэр, хариуцлагыг эмчилгээг гүйцэтгэж буй эмнэлэг, эмч нар хүлээнэ."
},

/* ══════════════════════ English ══════════════════════ */
en:{
  "util.reg":"Registered facilitator for international patients, Republic of Korea","util.regno":"No. A-2025-01-02-06146",
  "nav.about":"About","nav.service":"Services","nav.care":"Follow-up","nav.contact":"Contact","nav.cta":"Request consultation",

  "hero.eyebrow":"Global Patient Care · Korea",
  "hero.title":"A bridge of trust between<br>global patients and Korea's<br><b>leading university hospitals</b>",
  "hero.sub":"Official global partner of Kyung Hee University Medical Center and an official project operator for KHIDI. One team stays with the patient from pre-departure to post-return follow-up.",
  "hero.cta1":"Request a consultation","hero.cta2":"See our services",
  "hero.proverb":"Travel the road together and you will know your true companion.",
  "cred.1.t":"Official global partner, Kyung Hee University Medical Center",
  "cred.1.d":"Care is arranged under a hospital contract, not through an informal broker.",
  "cred.2.t":"Official KHIDI project operator",
  "cred.2.d":"Selected for the ICT-based pilot program for Mongolian critical-care patients and continuous follow-up.",
  "cred.3.t":"Licensed general travel business (No. 2025-000010)",
  "cred.3.d":"Flights, accommodation and transfers are arranged in-house under a travel business licence.",

  "biz.eyebrow":"Business Areas","biz.title":"Five lines of business",
  "biz.sub":"Bringing patients in is only the start. We build every stage of medical travel — treatment, recovery and training — into the business.",
  "biz.1.t":"Hospital liaison and concierge","biz.1.tag":"For Patients",
  "biz.1.d":"Critical care and comprehensive screening coordinated through formal links with Korean university hospitals, including Kyung Hee. One team handles record review, scheduling, interpretation and the stay itself.",
  "biz.2.t":"Wellness recovery travel","biz.2.tag":"For Patients",
  "biz.2.d":"The recovery period is designed as a journey: integrative Korean and Western medicine, convalescent programs, and itineraries for accompanying family — arranged in-house under our travel business licence.",
  "biz.3.t":"K-Food curation","biz.3.tag":"For Patients",
  "biz.3.d":"Recovery and immunity meal plans that follow the clinical team's guidance for patients, and a premium Korean dining experience — including royal court cuisine — for accompanying family.",
  "biz.4.t":"Clinical training for overseas physicians","biz.4.tag":"For Partners",
  "biz.4.d":"Placement of Mongolian and CIS physicians into fellowships and clinical training at Korean university hospitals. Local standards of care and the referral network grow together.",
  "biz.5.t":"Medical interpreter training","biz.5.tag":"For Partners",
  "biz.5.d":"We train interpreters who work in real clinical settings. An interpreter who understands terminology and care protocols is the sector's tightest bottleneck — and its most valuable asset.",

  "why.eyebrow":"Why Medijoy","why.title":"What sets Medijoy apart",
  "why.1.t":"Language and cultural fluency","why.1.l":"Beyond interpretation — understanding context.",
  "why.1.d":"Dedicated Mongolian interpreters remove the cultural misreadings that cause clinical misunderstanding, and keep patients at ease.",
  "why.2.t":"Concierge for the whole journey","why.2.l":"Assurance in unfamiliar surroundings.",
  "why.2.d":"From pre-departure preparation to a safe return home, end-to-end care minimises friction for the patient and accompanying family.",
  "why.3.t":"Transparent matching","why.3.l":"Less financial uncertainty, less anxiety.",
  "why.3.d":"Costs are explained in advance, and close coordination with the hospital keeps treatment to what is clinically necessary.",

  "home.j.eyebrow":"The Seamless Patient Journey","home.j.title":"One continuous handover, from departure to recovery at home",
  "home.j.sub":"A named coordinator owns each stage, and the patient and family deal with a single point of contact throughout.",
  "home.j.more":"See the full care process",

  "close.title":"Reassurance, trust and recovery — close to home",
  "close.sub":"So that treatment abroad never feels uncertain, Medijoy stays with you as your local partner.",
  "close.cta":"Request a consultation",

  "ab.crumb":"Home · About","ab.eyebrow":"About Medijoy","ab.title":"Medijoy puts people first",
  "ab.sub":"There is a person at both ends of every medical service. Reducing the anxiety a patient feels in an unfamiliar country is, to us, the substance of this business.",
  "ab.g.eyebrow":"CEO Message","ab.g.title":"A message from our CEO",
  "ab.g.1":"Thank you for considering Medijoy.",
  "ab.g.2":"Treatment across borders carries two difficulties. The first is <strong>reaching clinicians you can trust</strong>. The second is <strong>continuity of care once treatment ends</strong>. Many patients have cleared the first hurdle and stumbled on the second: the moment they fly home, the clinical record stops, and the local physician has no way of knowing what was done in Korea.",
  "ab.g.3":"Medijoy exists to join those two halves into one service. Our official partnership with Kyung Hee University Medical Center addresses the first; our own <strong>LiteracyM</strong> follow-up system addresses the second.",
  "ab.g.4":"A Mongolian proverb says: <em>“Travel the road together and you will know your true companion.”</em> Medijoy intends to walk the whole of that road with our patients.",
  "ab.g.sign":"Chief Executive, Medijoy","ab.g.name":"HAN MIN I",
  "ab.side.t":"At a glance",
  "ab.side.1":"Founded","ab.side.1v":"June 2025",
  "ab.side.2":"Focus","ab.side.2v":"International patient facilitation · care coordination",
  "ab.side.3":"Primary markets","ab.side.3v":"Mongolia · CIS · Eurasia",
  "ab.side.4":"Partner hospitals","ab.side.4v":"Kyung Hee University Medical Center and others",

  "ab.info.eyebrow":"Corporate Information","ab.info.title":"Company details and registrations",
  "ab.info.sub":"Medijoy holds both an international patient facilitator registration and a general travel business licence. Few operators hold both.",
  "ab.i.name":"Company","ab.i.namev":"MEDIJOY (메디조이)",
  "ab.i.ceo":"Representative","ab.i.ceov":"HAN MIN I",
  "ab.i.est":"Commenced","ab.i.estv":"9 June 2025",
  "ab.i.biz":"Business registration no.","ab.i.bizv":"455-63-00850",
  "ab.i.addr":"Address","ab.i.addrv":"B108-34, 30 Olympic-ro 78-gil, Gangdong-gu,<br>Seoul, Republic of Korea",
  "ab.i.type":"Lines of business","ab.i.typev":"International patient facilitation · travel agency · booking services · management consulting",
  "ab.i.reg1":"Facilitator registration","ab.i.reg1v":"No. A-2025-01-02-06146 (Mayor of Seoul)<br>Valid 23 Jun 2025 – 22 Jun 2028",
  "ab.i.reg2":"Tourism business registration","ab.i.reg2v":"No. 2025-000010, general travel business (Gangdong-gu Office)",
  "ab.i.tel":"Contact","ab.i.telv":"Tel. +82-2-477-1032 · Mobile. +82-10-8565-1032<br>contact@medijoy.co.kr",

  "adv.eyebrow":"Global Advisory Board","adv.title":"Three advisory pillars: clinical, pharmaceutical and international surgical",
  "adv.sub":"Cross-border medication safety, university-hospital clinical depth and an overseas surgical network combine into one treatment plan.",
  "adv.1.n":"Chulyong Kim, PharmD / CSO","adv.1.r":"Global pharmaceutical and bio specialist",
  "adv.1.a":"College of Pharmacy, Seoul National University","adv.1.b":"Specialty sales, Janssen Korea","adv.1.c":"16 years as owner-pharmacist, Daejo Pharmacy · operated a company in Ukraine",
  "adv.1.role":"Verifies cross-border drug equivalence and medication safety",
  "adv.2.n":"Prof. Sangho Lee","adv.2.r":"Nephrologist · Chief advisor",
  "adv.2.a":"Renal, transplant and cardiovascular critical care","adv.2.b":"Multidisciplinary care and global patient treatment protocols","adv.2.c":"Precision treatment roadmaps based on individual history",
  "adv.2.role":"Leads the pre-arrival clinical review for critical cases",
  "adv.3.n":"Dr. Shinyi Lee","adv.3.r":"Surgeon · International medical network",
  "adv.3.a":"Ph.D./M.D. in surgery, Moscow State Medical University","adv.3.b":"Former practising surgeon, Odesa, Ukraine","adv.3.c":"Local clinical liaison and follow-up for CIS and Eurasian patients",
  "adv.3.role":"Surgical exchange and multilingual clinical communication",

  "sv.crumb":"Home · Services","sv.eyebrow":"Our Service","sv.title":"One-stop care for international patients",
  "sv.sub":"From the pre-departure record review to remote follow-up after return, a single team designs and owns the whole journey.",
  "journey.eyebrow":"The Seamless Patient Journey","journey.title":"Managed in three stages",
  "journey.sub":"A named coordinator owns each stage, and the patient and family deal with a single point of contact throughout.",
  "j1.title":"Before arrival","j1.when":"Before Arrival",
  "j1.a.t":"Medical record review","j1.a.d":"Records are checked and reviewed in advance by a specialist.",
  "j1.b.t":"Hospital and physician matching","j1.b.d":"Matching to a verified hospital and care team.",
  "j1.c.t":"Travel arrangements","j1.c.d":"Visa support, accommodation recommendations and advance booking.",
  "j2.title":"In Korea","j2.when":"In Korea",
  "j2.a.t":"Arrival and transfers","j2.a.d":"Airport meet-and-greet with dedicated vehicle pickup and drop-off.",
  "j2.b.t":"Care coordination","j2.b.d":"One-to-one medical interpretation and appointment scheduling.",
  "j2.c.t":"24/7 support","j2.c.d":"Urgent issues handled through a live messenger channel.",
  "j3.title":"After return","j3.when":"After Return",
  "j3.a.t":"Follow-up care","j3.a.d":"Scheduled status checks and, when needed, remote follow-up with the Korean care team.",
  "j3.b.t":"Digital health records","j3.b.d":"Records managed through the LiteracyM app.",

  "prog.eyebrow":"Program Portfolio","prog.title":"Specialised care programs",
  "prog.1.t":"Critical care",
  "prog.1.a":"Kidney transplant, oncology and cardio-cerebrovascular disease.",
  "prog.1.b":"Integrated multidisciplinary care with senior clinical faculty, including Prof. Sangho Lee's team.",
  "prog.2.t":"Premium screening & wellness",
  "prog.2.a":"One-to-one comprehensive screening with a VIP health screening centre.",
  "prog.2.b":"Integrative Korean and Western medicine during the recovery period.",
  "prog.3.t":"K-gastronomy curation",
  "prog.3.a":"<strong>For patients:</strong> recovery and immunity meal plans that follow the clinical team's guidance (Medical Food Track).",
  "prog.3.b":"<strong>For accompanying family:</strong> a curated premium introduction to Korean cuisine.",

  "br.eyebrow":"Borderless Continuity of Care","br.title":"Treatment in Korea continues safely at home",
  "br.sub":"LiteracyM carries the record across the border to the patient's local physician.",
  "br.1.t":"Automatic record conversion","br.1.d":"Korean records and prescriptions are converted into Mongolian and handed to the local physician.",
  "br.2.t":"Smart monitoring","br.2.d":"Ongoing tracking of key values and medication adherence after return.",
  "br.3.t":"Included benefit","br.3.d":"Medijoy patients receive six months of LiteracyM at no cost.",
  "br.node1.s":"Kyung Hee University Medical Center","br.node1.d":"Precision diagnosis, surgery and treatment, producing a structured medical record.",
  "br.node2.s":"Patient & local physician","br.node2.d":"Continuous follow-up prescribing based on the translated clinical data.",

  "ct.crumb":"Home · Contact","ct.eyebrow":"Contact","ct.title":"Request a consultation",
  "ct.sub":"A dedicated coordinator reviews every request personally. Please write even if no diagnosis has been confirmed, or you are unsure where to start.",
  "form.title":"Consultation request","form.sub":"We reply within 24 business hours.",
  "form.name":"Full name","form.country":"Country of residence","form.other":"Other",
  "form.contact":"Phone or email","form.channel":"Preferred channel",
  "form.ch.phone":"Phone call","form.ch.email":"Email",
  "form.area":"Area of care",
  "form.area.critical":"Critical care (transplant, oncology, cardiovascular)",
  "form.area.checkup":"Premium comprehensive screening",
  "form.area.wellness":"Post-treatment recovery and wellness",
  "form.area.undecided":"Not decided yet",
  "form.docs":"Medical documents you already have (select all that apply)",
  "form.docs.hint":"No need to attach anything now. Just tell us what you have — our reply will explain how to send it securely.",
  "form.docs.1":"Medical records",
  "form.docs.2":"Laboratory results",
  "form.docs.3":"Imaging reports",
  "form.docs.4":"Nothing yet",
  "form.paid.t":"Pre-arrival clinical review (paid service)",
  "form.paid.d":"Where a detailed review by clinicians at a partner hospital is needed before arrival, it can be requested as a separate paid service. We explain the process and cost during the consultation.",
  "form.note":"Anything you would like us to know","form.note.ph":"Briefly describe the situation or your question.",
  "form.consent":"I consent to the collection and use of my personal data, and to its transfer abroad for consultation purposes. <a href=\"privacy.html\">Read the notice</a>",
  "form.submit":"Send request","form.sla":"We reply within 24 business hours of receiving your request.",
  "form.or":"or reach us on",
  "ct.info.t":"Reach us directly","ct.info.sub":"Phone consultations are available weekdays 09:00–18:00 Korea Standard Time.",
  "ct.i.tel":"Office","ct.i.mob":"Mobile","ct.i.mail":"Email","ct.i.addr":"Office address",
  "ct.i.addrv":"B108-34, 30 Olympic-ro 78-gil,<br>Gangdong-gu, Seoul, Republic of Korea",
  "ct.note.t":"Before you write",
  "ct.note.1":"Medijoy is not a medical institution and does not provide diagnoses by phone or online.",
  "ct.note.2":"Existing medical records or test results make the consultation far more precise. Our reply will explain how to send them.",
  "ct.note.3":"Treatability and estimated costs are confirmed only after clinical review.",

  "pv.crumb":"Home · Privacy policy","pv.eyebrow":"Privacy","pv.title":"Privacy policy",
  "pv.sub":"Medijoy protects personal data in accordance with the Personal Information Protection Act of the Republic of Korea. The Korean-language version is the authoritative text.",

  "ft.co":"MEDIJOY · Representative HAN MIN I",
  "ft.addr":"B108-34, 30 Olympic-ro 78-gil, Gangdong-gu, Seoul, Republic of Korea",
  "ft.biz":"Business registration no. 455-63-00850",
  "ft.reg":"Facilitator registration no. A-2025-01-02-06146 (valid 23 Jun 2025 – 22 Jun 2028)",
  "ft.tour":"Tourism business registration no. 2025-000010 · Gangdong-gu Office",
  "ft.privacy":"Privacy policy","ft.contact":"Contact","ft.about":"About","ft.service":"Services",
  "ft.disclaimer":"Medijoy is not a medical institution. As a registered facilitator for international patients, it provides liaison, interpretation and stay support between patients and Korean medical institutions. All medical decisions and responsibility for diagnosis and treatment rest with the treating institution and its clinicians."
}
};

/* ── apply ─────────────────────────────── */
function applyLang(lang){
  const dict = I18N[lang] || I18N.ko;
  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach(el=>{
    const v = dict[el.dataset.i18n]; if(v!=null) el.textContent = v;
  });
  document.querySelectorAll("[data-i18n-html]").forEach(el=>{
    const v = dict[el.dataset.i18nHtml]; if(v!=null) el.innerHTML = v;
  });
  document.querySelectorAll("[data-i18n-attr]").forEach(el=>{
    const [attr,key] = el.dataset.i18nAttr.split("|");
    const v = dict[key]; if(v!=null) el.setAttribute(attr, v);
  });
  document.querySelectorAll(".langs button").forEach(b=>{
    b.setAttribute("aria-current", String(b.dataset.lang===lang));
  });
  try{ localStorage.setItem("mj-lang", lang); }catch(e){}
}

function initSite(){
  document.querySelectorAll(".langs button").forEach(b=>{
    b.addEventListener("click", ()=>applyLang(b.dataset.lang));
  });
  const toggle = document.querySelector(".navtoggle");
  const nav = document.querySelector("nav.main");
  if(toggle && nav){
    toggle.addEventListener("click", ()=>{
      const open = nav.classList.toggle("open");
      toggle.setAttribute("aria-expanded", String(open));
    });
  }
  let initial = "ko";
  try{
    const saved = localStorage.getItem("mj-lang");
    if(saved && I18N[saved]) initial = saved;
    else if((navigator.language||"").toLowerCase().startsWith("mn")) initial = "mn";
    else if((navigator.language||"").toLowerCase().startsWith("zh")) initial = "zh";
    else if(!(navigator.language||"").toLowerCase().startsWith("ko")) initial = "en";
  }catch(e){}
  applyLang(initial);
}

document.addEventListener("DOMContentLoaded", initSite);
